/* ============================================================
   DATA
   ============================================================ */

const COUNTRIES = [
  {code:'US-CA', name:'United States \u2014 California', regs:['CCPA']},
  {code:'US-OTHER', name:'United States \u2014 other states', regs:[]},
  {code:'DE', name:'Germany', regs:['GDPR']},
  {code:'FR', name:'France', regs:['GDPR']},
  {code:'IT', name:'Italy', regs:['GDPR']},
  {code:'ES', name:'Spain', regs:['GDPR']},
  {code:'NL', name:'Netherlands', regs:['GDPR']},
  {code:'IE', name:'Ireland', regs:['GDPR']},
  {code:'PL', name:'Poland', regs:['GDPR']},
  {code:'SE', name:'Sweden', regs:['GDPR']},
  {code:'BE', name:'Belgium', regs:['GDPR']},
  {code:'AT', name:'Austria', regs:['GDPR']},
  {code:'PT', name:'Portugal', regs:['GDPR']},
  {code:'DK', name:'Denmark', regs:['GDPR']},
  {code:'FI', name:'Finland', regs:['GDPR']},
  {code:'GR', name:'Greece', regs:['GDPR']},
  {code:'CH', name:'Switzerland', regs:['GDPR'], note:true},
];

const GDPR_SCANNED = [
  {id:'gdpr-s1', code:'Art. 6', text:'Lawful basis referenced in privacy notice', sev:'high', na:false,
    layman:'Before collecting or using someone\u2019s personal data, you need a valid legal reason \u2014 like their consent, a contract with them, or a legitimate business need that doesn\u2019t override their rights.',
    articleTitle:'GDPR Article 6 \u2014 Lawfulness of processing',
    articleText:'Processing is only lawful if at least one condition applies: consent, necessity for a contract, a legal obligation, protecting someone\u2019s vital interests, a public-interest task, or a legitimate interest not overridden by the individual\u2019s rights.',
    proposals:['Create a data-processing register mapping every purpose you collect data for to one of the six legal bases.', 'Add a short "why we collect this" note next to each data type in your privacy notice.'],
    hints:{partial:'Lawful basis is referenced generically but not mapped to each processing purpose.', fail:'No documented lawful basis found for processing activities.'}},
  {id:'gdpr-s2', code:'Art. 7 / ePrivacy', text:'Granular consent mechanism for cookies and trackers', sev:'high', na:false,
    layman:'If your site uses cookies or trackers that aren\u2019t strictly necessary, you need to ask permission first \u2014 and it has to be a real choice, not a pre-checked box.',
    articleTitle:'GDPR Art. 7 & ePrivacy Directive \u2014 Conditions for consent',
    articleText:'Consent must be freely given, specific, informed, and unambiguous, shown through a clear affirmative action. It must be as easy to withdraw as to give, and bundling unrelated consents together isn\u2019t allowed.',
    proposals:['Make "Reject All" as prominent and one-click as "Accept All" in the cookie banner.', 'Split consent into categories (functional, analytics, marketing) so users can accept some and decline others.'],
    hints:{partial:'Cookie banner exists but lacks granular accept/reject-by-category controls.', fail:'No compliant consent mechanism detected \u2014 trackers appear to fire before consent.'}},
  {id:'gdpr-s3', code:'Art. 13', text:'Privacy notice covers all processing purposes in plain language', sev:'med', na:false,
    layman:'Your privacy policy needs to actually explain, in plain language, everything you do with someone\u2019s data \u2014 not just exist as a formality.',
    articleTitle:'GDPR Article 13 \u2014 Information to be provided',
    articleText:'When collecting data directly from someone, you must tell them who you are, why you\u2019re collecting their data, how long you\u2019ll keep it, who it\u2019s shared with, and what rights they have.',
    proposals:['Audit every data collection point on the site and confirm each purpose is named in the privacy notice.', 'Add a plain-language summary at the top of the policy, above the legal text.'],
    hints:{partial:'Notice covers most processing but omits some data sources found during the crawl.', fail:'Privacy notice is missing, or does not match tracking behavior observed on the site.'}},
  {id:'gdpr-s4', code:'Art. 37', text:'DPO contact designated and published', sev:'low', na:true,
    layman:'If your organization processes a lot of sensitive or large-scale personal data, you may be required to name a specific person responsible for privacy \u2014 and publish how to reach them.',
    articleTitle:'GDPR Article 37 \u2014 Designation of the data protection officer',
    articleText:'Certain organizations \u2014 including those doing large-scale monitoring or processing special categories of data \u2014 must appoint a Data Protection Officer and publish their contact details.',
    proposals:['Confirm whether your processing volume/type actually triggers the DPO requirement.', 'If required, publish a named or role-based contact (e.g. privacy@yourcompany.com) in the privacy policy.'],
    hints:{partial:'A privacy contact is listed but not clearly designated as DPO.', fail:'No Data Protection Officer or privacy contact designated.'}},
  {id:'gdpr-s5', code:'Ch. V', text:'International transfer safeguards disclosed', sev:'high', na:false,
    layman:'If you send European users\u2019 data to a country outside the EU (like the US), you need a legal safeguard in place so it stays protected once it leaves.',
    articleTitle:'GDPR Chapter V \u2014 Transfers of personal data to third countries',
    articleText:'Transfers outside the EEA are only allowed where the destination has an adequacy decision, or where safeguards like Standard Contractual Clauses (SCCs) or binding corporate rules are in place.',
    proposals:['Identify every vendor/subprocessor that stores or processes EU user data outside the EEA.', 'Put Standard Contractual Clauses in place with each vendor and reference them in your privacy policy.'],
    hints:{partial:'Transfers outside the EEA are mentioned but the underlying safeguard isn\u2019t named.', fail:'Cross-border data transfers detected with no documented safeguard.'}},
  {id:'gdpr-s6', code:'Art. 30', text:'Records-of-processing commitment referenced in policy', sev:'med', na:false,
    layman:'You\u2019re expected to keep an internal record of what personal data you collect, why, and where it goes \u2014 like an inventory of your own data practices.',
    articleTitle:'GDPR Article 30 \u2014 Records of processing activities',
    articleText:'Organizations must maintain a record of processing activities, including purposes, categories of data and recipients, and retention periods, available to regulators on request.',
    proposals:['Build an internal record cataloging each processing activity, purpose, and retention period.', 'Reference the existence of this record in your public privacy policy.'],
    hints:{partial:'A general commitment exists but the inventory scope looks incomplete.', fail:'No reference to a records-of-processing practice found.'}},
  {id:'gdpr-s7', code:'Art. 33', text:'Breach notification procedure documented', sev:'high', na:false,
    layman:'If you have a data breach, you\u2019re required to tell the relevant regulator within 72 hours of finding out \u2014 and in serious cases, tell affected users too.',
    articleTitle:'GDPR Article 33 \u2014 Notification of a personal data breach',
    articleText:'In the event of a breach likely to result in risk to individuals, the controller must notify the supervisory authority within 72 hours, and in high-risk cases, notify affected individuals directly.',
    proposals:['Write an incident-response runbook naming who owns the 72-hour regulator notification.', 'State your breach-notification commitment explicitly in the privacy policy.'],
    hints:{partial:'A breach process is referenced but the 72-hour window isn\u2019t specified.', fail:'No documented data breach notification procedure found.'}},
];

const GDPR_CHECKLIST = [
  {id:'gdpr-a1', code:'Art. 15', text:'Self-serve right to access \u2014 users can view/download their data from account settings', sev:'med',
    layman:'Users should be able to see and download a copy of what data you hold about them without emailing support and waiting.',
    articleTitle:'GDPR Article 15 \u2014 Right of access',
    articleText:'Individuals have the right to obtain confirmation of whether their data is being processed, and access to that data along with details of how it\u2019s used.',
    proposals:['Add a "View my data" / "Download my data" action inside account settings.', 'Make sure the export covers all data categories you actually hold.'],
    guidance:'Typically: an Account \u2192 Privacy or Data page with a "View my data" / "Download my data" action that works without emailing support.',
    followUp:'Is this available directly in account settings, and does it complete without a person manually processing it?',
    pos:['self-serve','self serve','instant','automatic','download','account settings','without contacting','no support','button','export'],
    neg:['email support','contact us','support ticket','manually','request via email','support team processes']},
  {id:'gdpr-a2', code:'Art. 17', text:'Self-serve right to erasure \u2014 users can delete their account/data without contacting support', sev:'high',
    layman:'Users should be able to delete their account and data themselves, without needing a person on your team to process it manually.',
    articleTitle:'GDPR Article 17 \u2014 Right to erasure ("right to be forgotten")',
    articleText:'Individuals can request deletion of their personal data where it\u2019s no longer needed, consent is withdrawn, or processing was unlawful, subject to limited exceptions.',
    proposals:['Add a self-serve "Delete my account" flow in settings with a clear stated timeline.', 'Document legal exceptions (e.g. billing records) so requests are handled consistently.'],
    guidance:'Typically: a "Delete my account" button in account settings that deletes immediately or within a stated window, with no email required.',
    followUp:'Can a user complete deletion entirely within your product UI, or does someone on your team take a manual step?',
    pos:['delete my account','self-serve','automatic','instant','account settings','button','without contacting'],
    neg:['email support','contact us','support ticket','manually processed','case-by-case']},
  {id:'gdpr-a3', code:'Art. 20', text:'Self-serve data portability \u2014 structured export (e.g. CSV/JSON)', sev:'low',
    layman:'If a user wants to take their data to another service, you need to give it to them in a format a computer can read \u2014 not just a PDF.',
    articleTitle:'GDPR Article 20 \u2014 Right to data portability',
    articleText:'Individuals have the right to receive their data in a structured, commonly used, machine-readable format, and to transmit it to another controller.',
    proposals:['Build a CSV or JSON export option alongside (or replacing) any PDF export.', 'Make the export accessible directly from account settings.'],
    guidance:'Typically: an export producing a machine-readable file (CSV/JSON) from account settings, not a manually compiled PDF.',
    followUp:'Does the export come out as a structured, machine-readable file, or as something a person put together?',
    pos:['csv','json','export','machine-readable','structured','download','self-serve'],
    neg:['pdf summary','manually compiled','email attachment','support prepares']},
  {id:'gdpr-a4', code:'Art. 7 (ongoing)', text:'Granular consent preference center \u2014 marketing/analytics/tracking toggled independently', sev:'med',
    layman:'Users should be able to manage privacy preferences (like marketing vs. analytics tracking) individually, not just one all-or-nothing toggle.',
    articleTitle:'GDPR Article 7 (ongoing) \u2014 Withdrawing and managing consent',
    articleText:'Consent must be as easy to withdraw as to give, and where multiple purposes exist, consent should be obtainable and withdrawable separately for each.',
    proposals:['Build a preferences page with independent toggles per category (marketing, analytics, personalization).', 'Make sure withdrawing one consent doesn\u2019t silently affect unrelated settings.'],
    guidance:'Typically: a preferences page where each consent category has its own toggle, not one blanket accept-all switch.',
    followUp:'Can a user turn off, say, marketing while keeping analytics on, independently of each other?',
    pos:['toggle','independently','granular','separate','preference center','opt out of','turn off'],
    neg:['all or nothing','single toggle','accept all only','one setting']},
];

const CCPA_SCANNED = [
  {id:'ccpa-s1', code:'\u00A71798.135', text:'"Do Not Sell or Share My Personal Information" link present', sev:'high', na:false,
    layman:'California users need a clearly visible link letting them opt out of having their data sold or shared \u2014 usually in the footer.',
    articleTitle:'CCPA \u00A71798.135 \u2014 Right to opt-out',
    articleText:'Businesses that sell or share personal information must provide a clear and conspicuous "Do Not Sell or Share My Personal Information" link allowing consumers to opt out.',
    proposals:['Move the opt-out link out of a buried sub-menu into the main footer.', 'Make sure the link actually triggers the opt-out rather than just linking to an explainer page.'],
    hints:{partial:'The link exists but is buried in footer navigation rather than prominent.', fail:'No "Do Not Sell or Share My Personal Information" link found.'}},
  {id:'ccpa-s2', code:'\u00A71798.100', text:'Notice at collection describing categories and purposes', sev:'high', na:false,
    layman:'Before or when you collect someone\u2019s data, you need to tell them what categories you\u2019re collecting and why \u2014 not bury it in a long policy.',
    articleTitle:'CCPA \u00A71798.100 \u2014 Notice at collection',
    articleText:'Businesses must inform consumers, at or before the point of collection, of the categories of personal information collected and the purposes they\u2019ll be used for.',
    proposals:['Add a short notice at each data-collection point (forms, sign-up) listing what\u2019s collected and why.', 'Cross-check the notice against everything actually being collected.'],
    hints:{partial:'A notice is present but doesn\u2019t list all categories of personal information collected.', fail:'No notice at collection shown before or at the point of data collection.'}},
  {id:'ccpa-s3', code:'\u00A71798.125', text:'Non-discrimination commitment stated in policy', sev:'med', na:false,
    layman:'You\u2019re not allowed to punish users \u2014 like giving them a worse product or higher prices \u2014 just because they exercised their privacy rights.',
    articleTitle:'CCPA \u00A71798.125 \u2014 Non-discrimination',
    articleText:'Businesses may not deny goods or services, charge different prices, or provide a different level of service because a consumer exercised a CCPA right.',
    proposals:['Add an explicit non-discrimination statement to the privacy policy.', 'Audit account tiers/pricing to confirm opting out doesn\u2019t quietly downgrade the experience.'],
    hints:{partial:'Policy language exists but doesn\u2019t explicitly rule out degraded service for opt-outs.', fail:'No non-discrimination commitment found in the policy.'}},
  {id:'ccpa-s4', code:'\u00A71798.121', text:'Sensitive personal information opt-out link present', sev:'high', na:false,
    layman:'Beyond the general opt-out, California users get an extra right to limit how you use more sensitive info (health, precise location, financial data).',
    articleTitle:'CCPA \u00A71798.121 \u2014 Right to limit use of sensitive personal information',
    articleText:'Consumers have the right to direct a business to limit its use of sensitive personal information to what\u2019s necessary to provide the requested goods or services.',
    proposals:['Add a distinct "Limit the Use of My Sensitive Personal Information" link, separate from the general opt-out.', 'Confirm what counts as sensitive PI in your data model first.'],
    hints:{partial:'A "limit use" link is present but not clearly distinguished from the general opt-out.', fail:'No link to limit use of sensitive personal information found.'}},
  {id:'ccpa-s5', code:'\u00A71798.125(b)', text:'Financial incentive program disclosure (if applicable)', sev:'low', na:true,
    layman:'If you offer users a discount or perk in exchange for their data (like a loyalty program), you have to clearly explain that trade-off.',
    articleTitle:'CCPA \u00A71798.125(b) \u2014 Financial incentive disclosures',
    articleText:'Businesses offering financial incentives in exchange for personal information must disclose the material terms of the program and obtain opt-in consent.',
    proposals:['If you run a loyalty/rewards program, publish the specific data-for-benefit terms.', 'Add an explicit opt-in step before enrolling users in any incentive program involving their data.'],
    hints:{partial:'A loyalty/rewards program exists but incentive terms aren\u2019t fully disclosed.', fail:'A financial incentive program was detected without the required disclosure.'}},
];

const CCPA_CHECKLIST = [
  {id:'ccpa-a1', code:'\u00A71798.110', text:'Self-serve right to know/access from account settings', sev:'med',
    layman:'California users should be able to see what categories of data you have on them directly from their account, not by filing a request and waiting.',
    articleTitle:'CCPA \u00A71798.110 \u2014 Right to know',
    articleText:'Consumers have the right to request the specific pieces and categories of personal information a business has collected about them.',
    proposals:['Add a "What we know about you" view inside account settings.', 'Keep it in sync with what\u2019s actually collected, not a static summary.'],
    guidance:'Typically: an account page listing categories of personal info collected, viewable/downloadable without contacting support.',
    followUp:'Can a user see this directly in their account, or does it require submitting a request and waiting?',
    pos:['self-serve','account settings','view','download','automatic','without contacting'],
    neg:['email','contact us','support ticket','wait for response','manually']},
  {id:'ccpa-a2', code:'\u00A71798.105', text:'Self-serve right to delete from account settings', sev:'high',
    layman:'Users should be able to delete their account and personal data themselves, directly in the product, not by emailing support.',
    articleTitle:'CCPA \u00A71798.105 \u2014 Right to delete',
    articleText:'Consumers have the right to request deletion of personal information collected about them, subject to certain business exceptions.',
    proposals:['Add a self-serve account deletion flow with a clear completion timeline.', 'List legal retention exceptions so deletion requests are handled consistently.'],
    guidance:'Typically: a "Delete my account" option in settings that completes the request without emailing support.',
    followUp:'Does deletion happen directly through account settings, or does someone process it manually?',
    pos:['delete my account','self-serve','automatic','account settings','button'],
    neg:['email','contact us','support ticket','manually','case-by-case']},
  {id:'ccpa-a3', code:'\u00A71798.106', text:'Self-serve right to correct from account settings', sev:'med',
    layman:'Users should be able to fix wrong information about themselves directly, not have to ask someone on your team to do it.',
    articleTitle:'CCPA \u00A71798.106 \u2014 Right to correct',
    articleText:'Consumers have the right to request correction of inaccurate personal information a business maintains about them.',
    proposals:['Make profile fields directly editable wherever possible.', 'For fields that can\u2019t be self-edited, add a lightweight correction-request form inside the account.'],
    guidance:'Typically: an editable profile/settings page where users can directly correct inaccurate personal information.',
    followUp:'Can users edit this themselves in their account, or does your team make the change?',
    pos:['edit','self-serve','account settings','directly','update'],
    neg:['email','contact us','support makes the change','manually']},
  {id:'ccpa-a4', code:'\u00A71798.121', text:'Sensitive-PI "limit use" toggle actually functions (not just a static link)', sev:'med',
    layman:'The "limit use of sensitive info" option needs to be a real, working setting \u2014 not just a link to a policy page that doesn\u2019t change anything.',
    articleTitle:'CCPA \u00A71798.121 \u2014 Right to limit use of sensitive personal information (functional check)',
    articleText:'The right to limit use of sensitive personal information must be operable by the consumer, not merely described.',
    proposals:['Wire the "limit use" toggle to an actual backend flag that changes how sensitive data is used/shared.', 'Add confirmation feedback when a user turns the toggle on.'],
    guidance:'Typically: a real toggle in account/privacy settings that restricts use of sensitive personal information, not just an informational link.',
    followUp:'Is this an actual working toggle in the account, or just a link to a policy page?',
    pos:['toggle','setting','account','functions','actually limits','opt out'],
    neg:['just a link','static page','informational only','no setting']},
];

const FINES = {
  'gdpr-s2': {who:'Mid-size adtech network (composite case)', violation:'Trackers fired before consent was captured', fine:'\u20AC8.4M', regulator:'EU Data Protection Authority', year:2023},
  'gdpr-a2': {who:'SaaS analytics platform (composite case)', violation:'No functioning erasure / deletion mechanism', fine:'\u20AC2.1M', regulator:'EU Data Protection Authority', year:2022},
  'gdpr-s5': {who:'Financial services site (composite case)', violation:'Cross-border transfers without documented safeguards', fine:'\u20AC12.0M', regulator:'EU Data Protection Authority', year:2023},
  'ccpa-s1': {who:'Regional retail chain (composite case)', violation:'No functioning "Do Not Sell" link', fine:'$1.2M', regulator:'California Attorney General', year:2023},
  'ccpa-s2': {who:'Media publisher (composite case)', violation:'Missing notice at collection', fine:'$0.9M', regulator:'California Attorney General', year:2022},
  'ccpa-a4': {who:'Consumer app (composite case)', violation:'Undisclosed sharing of sensitive personal information', fine:'$3.7M', regulator:'California Attorney General', year:2024},
};

const BILLS = [
  {name:'EU AI Act \u2014 high-risk system obligations', region:'EU', status:'Enforcement phasing in', effective:'Phased 2025\u20132027',
   summary:'Sets tiered obligations for AI systems by risk level, with the strictest rules applying to "high-risk" use cases like automated decision-making.',
   relevance:'Relevant if the site uses AI-driven personalization, scoring, or automated decisions on EU users.',
   prep:'Inventory AI-driven features on the site and classify each by risk tier.'},
  {name:'American Privacy Rights Act (APRA)', region:'US-Federal', status:'Proposed', effective:'TBD',
   summary:'A proposed federal privacy standard that would preempt parts of the current state-by-state patchwork.',
   relevance:'Would eventually replace or layer on top of state laws currently used for compliance.',
   prep:'Track committee status; avoid building compliance solely around the current state patchwork.'},
  {name:'Colorado Privacy Act \u2014 profiling amendments', region:'US-Colorado', status:'In effect', effective:'2024\u20132026 phased',
   summary:'Adds specific obligations around profiling used for consequential decisions (housing, employment, credit, etc).',
   relevance:'Applies if the site profiles Colorado residents for decisions with legal or similarly significant effects.',
   prep:'Add an opt-out specifically for profiling used in consequential decisions.'},
  {name:'California Delete Act (SB 362)', region:'US-California', status:'Passed, phasing in', effective:'2026',
   summary:'Creates a one-click deletion mechanism across registered data brokers via the DROP portal.',
   relevance:'Relevant if the site sells or shares data with registered data brokers.',
   prep:'Confirm data-broker registration status if the site shares data with brokers.'},
  {name:'California AI Transparency Act (SB 942)', region:'US-California', status:'In effect', effective:'2026',
   summary:'Requires provenance disclosures and detection tools for generative AI content offered to California users.',
   relevance:'Relevant if the site offers generative AI features to California users.',
   prep:'Add AI content provenance disclosures if generative features are in use.'},
  {name:'LGPD enforcement ramp-up', region:'Brazil', status:'In effect', effective:'Ongoing',
   summary:'Brazil\u2019s national data protection authority (ANPD) continuing to increase enforcement activity and guidance.',
   relevance:'Relevant if the site serves Brazilian users or processes their data.',
   prep:'Confirm a data controller is designated for Brazilian operations.'},
  {name:'Consumer Privacy Protection Act (Bill C-27)', region:'Canada', status:'Proposed / reintroduction expected', effective:'TBD',
   summary:'Would modernize PIPEDA with GDPR-like rights including stronger consent and portability provisions.',
   relevance:'Would raise the bar above current PIPEDA obligations if the site serves Canadian users.',
   prep:'Monitor status; current PIPEDA obligations still apply in the meantime.'},
  {name:'UK Data (Use and Access) reforms', region:'UK', status:'Passed, phasing in', effective:'2025\u20132026',
   summary:'Adjusts UK GDPR in areas like cookie-consent exemptions and legitimate-interest processing.',
   relevance:'Relevant if the site processes UK residents\u2019 data under UK GDPR, which is diverging gradually from EU GDPR.',
   prep:'Watch for updated cookie-consent exemption rules that may simplify some banners.'},
];

const TRUST_CATS = [
  {id:'minimization', name:'Data minimization',
   notes:{good:'Collection appears scoped to stated purposes \u2014 keep auditing fields as forms change.',
           moderate:'Some optional fields are collected without a clearly stated purpose. Tag each field with a retention/purpose reason.',
           weak:'Forms request more data than the stated purpose requires. Cut optional fields and require justification for any new one added.'}},
  {id:'consent', name:'Consent clarity',
   notes:{good:'Consent language is specific and avoids bundling unrelated permissions together.',
           moderate:'Consent copy is understandable but bundles marketing and functional cookies together \u2014 separate them.',
           weak:'Consent language is dense legal text with no plain-language summary above it.'}},
  {id:'rights', name:'User rights support',
   notes:{good:'Access, delete, and export flows are self-service and confirm completion to the user.',
           moderate:'Rights exist but require emailing support, which adds friction and delay.',
           weak:'No visible self-service path exists for users to exercise their data rights.'}},
  {id:'thirdparty', name:'Third-party transparency',
   notes:{good:'Sub-processors and ad/analytics partners are named with an up-to-date list.',
           moderate:'Third parties are referenced generically ("partners") without a named list.',
           weak:'There is no disclosure of which third parties receive user data.'}},
  {id:'retention', name:'Retention specificity',
   notes:{good:'Retention periods are stated per data category, not just "as long as necessary."',
           moderate:'A general retention statement exists but isn\u2019t broken out by data type.',
           weak:'No retention period is stated anywhere in the policy.'}},
];

const SEV_WEIGHT = {high:3, med:2, low:1};
const SEV_LABEL = {high:'High severity', med:'Medium severity', low:'Low severity'};
const STALE_DAYS = 90;
